### ISSUE TITLE
Connection ended

### ISSUE THREAD

**Issue by WarL0ckNet** [LDarki/NodeJS-DuinoCoin-Miner#5]
Connection ended
(node:2624540) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at startMining (/home/warl0ck/tools/NodeJS-DuinoCoin-Miner/index.js:96:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2624540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2624540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by WarL0ckNet** [comment]
You wrong send hashrate in line:
`socket.write(i.toString() + ","+data.hashes+",NodeJS Miner v2.0");`

In https://github.com/revoxhere/duino-coin/blob/master/PC_Miner.py send this:
```
                time_elapsed = time() - time_start
                hashrate = nonce / time_elapsed
                return [nonce, hashrate]
```

**Comment by LDarki** [comment]
Hi, sorry for the late response.

It is interesting.
because it works fine to me.

I will update the code, please try again.

I apologize for this.
